### ISSUE TITLE
User can login and register username

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/mock-twitter#4]
![screen shot 2016-09-01 at 4 12 00 pm](https://cloud.githubusercontent.com/assets/19194235/18187582/a7e7365a-705f-11e6-8fdc-63e08c98c81f.png)

**Comment by farookisonfire** [comment]
Feature edit:
- going to scrap the picture upload

**Comment by farookisonfire** [comment]
Login Modal:

![screen shot 2016-09-02 at 4 24 18 pm](https://cloud.githubusercontent.com/assets/19194235/18220834/afa695fe-712a-11e6-82d9-a56fe7242f4b.png)

**Comment by farookisonfire** [comment]
Remaining Requirements:
- Login button functionality

**Comment by farookkhan** [comment]
http://g.recordit.co/eCjx7Tb0yp.gif

**Comment by farookkhan** [comment]
`<a href="http://www.dazzlejunction.com/generators/image-generator.php" title="html image code" target="_blank"><img src="http://g.recordit.co/eCjx7Tb0yp.gif" border="0"></a>`

**Comment by farookisonfire** [comment]
![twitta home](https://cloud.githubusercontent.com/assets/19194235/18257602/56414e3e-737b-11e6-947f-af2224d233c5.gif)

**Comment by farookisonfire** [comment]
![twitta - register user](https://cloud.githubusercontent.com/assets/19194235/18257427/523f54e6-7378-11e6-87f5-de802238ce6c.gif)
