### ISSUE TITLE
User can re-tweet another post

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/mock-twitter#5]
![screen shot 2016-09-01 at 4 15 05 pm](https://cloud.githubusercontent.com/assets/19194235/18187593/bdeeb46e-705f-11e6-9de9-eb5d876fa142.png)

**Comment by farookkhan** [comment]
![retweet](https://cloud.githubusercontent.com/assets/19194235/18331051/0bd96d6c-7511-11e6-8083-778bdc540c69.gif)

**Comment by farookisonfire** [comment]
![retweet](https://cloud.githubusercontent.com/assets/19194235/18331073/2c2559b4-7511-11e6-82e7-7e841020ef15.gif)

**Comment by farookisonfire** [comment]
Remaining Requirements:
- Styling the retweet button

**Comment by farookkhan** [comment]
![retweeting and unretweeting](https://cloud.githubusercontent.com/assets/19194235/18369647/f57ff0d8-75db-11e6-9c4e-02120c31fdc1.gif)

**Comment by farookisonfire** [comment]
![retweeting and unretweeting](https://cloud.githubusercontent.com/assets/19194235/18369681/21d5ee08-75dc-11e6-9f63-f3cedb063bc3.gif)

**Comment by farookisonfire** [comment]
Remaining Requirement:
- When un-retweeting, the original tweet should remain.
